### ISSUE TITLE
这是一个针对微信的吗？

### ISSUE THREAD

**Issue by onestar1** [KevinWG/OSS.Core#1]
看了您的几个项目， 我是想请教下 这个oss.core项目是整合你其他的类库吗？

**Comment by KevinWG** [comment]
对，会整合其他项目，最近工作变动，更新会慢一些

**Comment by onestar1** [comment]
研究学习了下， 不过看到 很多 wwwroot 跟控制器 都是空的？
![image](https://cloud.githubusercontent.com/assets/10646303/26272255/7b6cca68-3d46-11e7-9696-56802b7c6bc1.png)

**Comment by KevinWG** [comment]
现在主要集中在webapi开发，website即将开始
